name: Build and push Docker container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container
        run: >
          docker buildx build --push
          --platform linux/amd64,linux/arm/v7,linux/arm64/v8
          --build-arg SOURCE_COMMIT=$GITHUB_SHA
          -t "ghcr.io/sgsunder/samba:latest"
          .
